name: shobai_ten
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  dio: ^5.4.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  share: ^2.0.0
  flutter_local_notifications:
  shared_preferences:
  
  
 

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter
  provider: ^6.1.1
  http:
  intl:
  flutter_session_manager: ^1.0.3
  flutter_facebook_auth:
 
 

flutter: 
  uses-material-design: true
  assets:
   - assets/

